drupalAcctProvisionServer: uc_ldap
ldapEntryProvisionServer: null
drupalAcctProvisionTriggers:
  drupal_on_login: drupal_on_login
  drupal_on_update_create: '0'
ldapEntryProvisionTriggers:
  ldap_on_update_create: '0'
  ldap_on_login: '0'
  ldap_on_delete: '0'
  drupal_on_manual_creation: '0'
orphanedDrupalAcctBehavior: ldap_user_orphan_email
orphanedCheckQty: 100
orphanedAccountCheckInterval: weekly
userConflictResolve: resolve
manualAccountConflict: conflict_associate
acctCreation: ldap_behaviour
ldapUserSyncMappings:
  drupal: {  }
  ldap: {  }
_core:
  default_config_hash: EF5h9g_BZcwXGICZHc3HiF9BxhEhGo4ZiPFRWTq0Ka4
userUpdateCronQuery: none
userUpdateCronInterval: monthly
disableAdminPasswordField: false
