channels:
  -
    id: diagnostics
    grants:
      - 3
  -
    id: purgers
    grants:
      - 0
      - 2
      - 3
  -
    id: queue
    grants:
      - 0
      - 2
      - 3
  -
    id: purger_varnish_3b5ca7f8f9
    grants:
      - 0
      - 2
      - 3
  -
    id: purger_acquia_purge_ec52b02fa6
    grants:
      - 0
      - 2
      - 3
  -
    id: purger_cloudfront_e23d1d9993
    grants:
      - 0
      - 2
      - 3
